/**
 * AiExplanation — a human-readable breakdown of why the AI reached a
 * particular decision.  Generated by the ExplainabilityEngine.
 */
export interface RuleContribution {
  /** Rule id that contributed. */
  ruleId: string;
  ruleName: string;
  /** Normalised contribution to the final decision (0–1). */
  contribution: number;
  /** Value of the feature that triggered this rule. */
  triggerValue: number;
  /** Threshold the feature crossed. */
  threshold: number;
  /** Short phrase: "velocity (0.3) fell below threshold (1.0)". */
  explanation: string;
}

export interface FeatureImportance {
  featureName: string;
  /** Normalised importance across all fired rules (0–1). */
  importance: number;
  currentValue: number;
  /** Direction of influence on the decision outcome. */
  direction: 'positive' | 'negative' | 'neutral';
}

export interface AiExplanation {
  decisionId: string;
  /** Single sentence capturing the decision. */
  summary: string;
  ruleContributions: RuleContribution[];
  featureImportance: FeatureImportance[];
  /** 0–100 overall engine confidence. */
  confidence: number;
  /** Multi-sentence plain-language rationale suitable for end-user display. */
  humanReadable: string;
}
