import type { TajweedRuleType } from './tajweed-rule-application.entity';

/**
 * AdaptivePlan — a personalised weekly study plan generated by the
 * AdaptiveLearningEngine.
 */

export interface FocusArea {
  area: 'tajweed' | 'memorization' | 'review' | 'pronunciation';
  /** Specific items to focus on, e.g. rule names or ayah ranges. */
  specifics: string[];
  /** Priority order (1 = most urgent). */
  priority: number;
  /** Estimated weeks to reach proficiency in this area. */
  estimatedImprovementWeeks: number;
}

export interface DaySchedule {
  /** 0 = Sunday … 6 = Saturday. */
  dayOfWeek: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  sessionMinutes: number;
  newAyahsTarget: number;
  reviewAyahsTarget: number;
  tajweedPractice: boolean;
  /** Optional recommended time-of-day for best retention. */
  preferredTimeOfDay?: 'morning' | 'afternoon' | 'evening';
}

export interface AdaptivePlan {
  /** Recommended weekly new-memorization pace (ayahs/week). */
  adjustedWeeklyPace: number;
  /** Difficulty level 1 (beginner) – 5 (advanced). */
  difficultyLevel: number;
  /**
   * Proportion of study time dedicated to review (0 = all new, 1 = all review).
   */
  reviewEmphasis: number;

  weeklySchedule: DaySchedule[];
  focusAreas: FocusArea[];

  /** Tajweed rules that need the most attention this cycle. */
  tajweedFocusRules: TajweedRuleType[];

  estimatedWeeksToGoal: number;

  /** Human-readable rationale explaining each major adjustment. */
  rationale: string[];
}
