/**
 * AiRecommendation — a single actionable recommendation generated by
 * the AI Recommendation Engine and surfaced to students, sheikhs or
 * parents.
 */

export type AiRecommendationType =
  | 'focus_tajweed_rule'
  | 'increase_review_frequency'
  | 'reduce_new_memorization'
  | 'target_difficult_words'
  | 'practice_specific_surah'
  | 'improve_pronunciation'
  | 'extend_session_length'
  | 'reduce_session_length'
  | 'morning_study_recommended'
  | 'address_systematic_mistake'
  | 'celebrate_milestone'
  | 'adjust_difficulty_down'
  | 'adjust_difficulty_up'
  | 'consistency_alert'
  | 'forgetting_curve_alert';

export type AiRecommendationTarget =
  | 'tajweed'
  | 'memorization'
  | 'review'
  | 'practice'
  | 'general';

export interface AiRecommendation {
  type: AiRecommendationType;
  priority: 'critical' | 'high' | 'medium' | 'low';
  title: string;
  description: string;
  /** Ordered list of concrete steps the student can take. */
  actionItems: string[];
  /**
   * Estimated improvement in overall performance if followed (0–100).
   * Used to sort recommendations when many fire simultaneously.
   */
  estimatedImpact: number;
  /** How confident the engine is in this recommendation (0–100). */
  confidenceScore: number;
  /** Signal names that caused this rule to fire. */
  triggeredBy: string[];
  targetArea: AiRecommendationTarget;
}
