/**
 * AudioRecommendationType — the category of actionable advice generated
 * from audio analysis. Distinct from IntelligenceRecommendationType so the
 * two recommendation systems remain independently typed.
 */
export type AudioRecommendationType =
  | 'tajweed_practice'     // Specific tajweed rule needs practice
  | 'pronunciation'        // Pronunciation accuracy
  | 'fluency'              // Pace and flow improvement
  | 'memorization_gap'     // Words/ayahs missing from audio (alignment gaps)
  | 'consistency'          // Uneven performance across segments
  | 'positive_feedback';   // Reinforcement when score is high

export type AudioRecommendationPriority = 'high' | 'medium' | 'low';

/**
 * AudioRecommendation — a single, actionable piece of advice generated by
 * AudioRecommendationEngine from the audio analysis results.
 *
 * Recommendations are grounded entirely in the audio session analysis —
 * mistakes, tajweed observations, and scores. No LLM involved.
 *
 * Embedded in AudioSession.recommendations (one session → many recs).
 */
export interface AudioRecommendation {
  type: AudioRecommendationType;
  priority: AudioRecommendationPriority;

  /** Short, human-readable title (≤ 60 characters). */
  title: string;

  /** Specific, actionable description (≤ 300 characters). */
  description: string;

  /** The rule key that triggered this recommendation (for traceability). */
  triggeredBy: string;

  /** Whether there is a clear immediate action for the student. */
  actionable: boolean;

  /**
   * Optional quantitative target.
   * e.g. { unit: 'counts', value: 4, period: 'per madd' }
   */
  target?: { unit: string; value: number; period?: string };

  /**
   * The specific tajweed rule this recommendation addresses.
   * Present for type === 'tajweed_practice'.
   */
  tajweedRule?: string;
}
