import { Controller, Get, Param } from '@nestjs/common';
import { ApiOperation, ApiParam, ApiTags } from '@nestjs/swagger';
import { RequirePermissions } from '@common/decorators/require-permissions.decorator';
import { CurrentUser } from '@modules/auth/infrastructure/decorators/current-user.decorator';
import { AccessTokenPayload } from '@modules/auth/domain/value-objects/jwt-payload';
import { PERMISSIONS } from '@shared/authorization/permission-registry';

import { GetStudentIntelligenceProfileUseCase } from '../../application/use-cases/get-student-intelligence-profile.use-case';
import { GetStudentRecommendationsUseCase } from '../../application/use-cases/get-student-recommendations.use-case';
import { GetStudentIntelligenceForecastUseCase } from '../../application/use-cases/get-student-intelligence-forecast.use-case';
import { StudentIntelligenceProfileDto } from '../../application/dtos/student-intelligence-profile.dto';
import { StudentRecommendationsDto } from '../../application/dtos/recommendation.dto';
import { IntelligenceForecastDto } from '../../application/dtos/intelligence-forecast.dto';

/**
 * IntelligenceController — Phase 13A.
 *
 * Student-centric intelligence endpoints. All computation is local and
 * deterministic — no external AI service is called.
 *
 * Base path: /intelligence/students/:studentId
 */
@ApiTags('Intelligence')
@Controller('intelligence/students')
export class IntelligenceController {
  constructor(
    private readonly getProfile: GetStudentIntelligenceProfileUseCase,
    private readonly getRecommendations: GetStudentRecommendationsUseCase,
    private readonly getForecast: GetStudentIntelligenceForecastUseCase,
  ) {}

  @Get(':studentId/profile')
  @RequirePermissions(PERMISSIONS.INTELLIGENCE.READ!)
  @ApiOperation({
    summary: 'Get student intelligence profile',
    description:
      'Returns a fully computed intelligence profile for a student: ' +
      '10 diagnostic scores, temporal learning patterns, pace metrics, ' +
      'and risk classifications. Computed entirely from platform data — ' +
      'no external AI service is involved.',
  })
  @ApiParam({ name: 'studentId', description: 'Student profile ID or own userId (for STUDENT role)' })
  async getStudentProfile(
    @CurrentUser() user: AccessTokenPayload,
    @Param('studentId') studentId: string,
  ): Promise<StudentIntelligenceProfileDto> {
    const profile = await this.getProfile.execute(user, studentId);
    return {
      studentId: profile.studentId,
      generatedAt: profile.generatedAt.toISOString(),
      memorizationScore: profile.memorizationScore,
      revisionScore: profile.revisionScore,
      consistencyScore: profile.consistencyScore,
      attendanceScore: profile.attendanceScore,
      difficultyIndex: profile.difficultyIndex,
      forgettingRisk: profile.forgettingRisk,
      bestMemorizationTime: profile.bestMemorizationTime,
      bestRevisionTime: profile.bestRevisionTime,
      learningSpeed: profile.learningSpeed,
      retentionRate: profile.retentionRate,
      dailyPaceAyahs: profile.dailyPaceAyahs,
      weeklyPaceAyahs: profile.weeklyPaceAyahs,
      activeDaysLast30: profile.activeDaysLast30,
      totalAyahsMemorized: profile.totalAyahsMemorized,
      memorizationPercentage: profile.memorizationPercentage,
      overdueRevisionCount: profile.overdueRevisionCount,
      revisionBurdenScore: profile.revisionBurdenScore,
      totalOpenMistakes: profile.totalOpenMistakes,
      dominantMistakeType: profile.dominantMistakeType,
      mistakeResolutionRate: profile.mistakeResolutionRate,
    };
  }

  @Get(':studentId/recommendations')
  @RequirePermissions(PERMISSIONS.INTELLIGENCE.READ!)
  @ApiOperation({
    summary: 'Get personalised recommendations for a student',
    description:
      'Returns up to 8 ranked recommendations generated by the rule-based ' +
      'RecommendationEngine. Each recommendation is grounded in specific ' +
      'platform data with a triggeredBy field for full explainability.',
  })
  @ApiParam({ name: 'studentId', description: 'Student profile ID or own userId (for STUDENT role)' })
  async getStudentRecommendations(
    @CurrentUser() user: AccessTokenPayload,
    @Param('studentId') studentId: string,
  ): Promise<StudentRecommendationsDto> {
    const result = await this.getRecommendations.execute(user, studentId);
    return {
      studentId: result.studentId,
      generatedAt: result.generatedAt.toISOString(),
      recommendations: result.recommendations,
      total: result.recommendations.length,
      highPriorityCount: result.recommendations.filter(r => r.priority === 'high').length,
    };
  }

  @Get(':studentId/forecast')
  @RequirePermissions(PERMISSIONS.INTELLIGENCE.READ!)
  @ApiOperation({
    summary: 'Get intelligence-enhanced Quran completion forecast',
    description:
      'Returns raw and revision-burden-adjusted completion forecasts, ' +
      'overdue revision metrics, and risk classification. ' +
      'Entirely deterministic — no external AI calls.',
  })
  @ApiParam({ name: 'studentId', description: 'Student profile ID or own userId (for STUDENT role)' })
  async getStudentForecast(
    @CurrentUser() user: AccessTokenPayload,
    @Param('studentId') studentId: string,
  ): Promise<IntelligenceForecastDto> {
    const result = await this.getForecast.execute(user, studentId);
    return {
      studentId: result.studentId,
      generatedAt: result.generatedAt.toISOString(),
      totalAyahsMemorized: result.totalAyahsMemorized,
      remainingAyahs: result.remainingAyahs,
      memorizationPercentage: result.memorizationPercentage,
      estimatedDaysRemaining: result.estimatedDaysRemaining,
      estimatedCompletionDate: result.estimatedCompletionDate,
      adjustedDaysRemaining: result.adjustedDaysRemaining,
      adjustedCompletionDate: result.adjustedCompletionDate,
      revisionBurdenScore: result.revisionBurdenScore,
      overdueRevisionCount: result.overdueRevisionCount,
      weeklyRevisionNeededToClearBacklog: result.weeklyRevisionNeededToClearBacklog,
      completionRisk: result.completionRisk,
      paceLabel: result.paceLabel,
      consistencyScore: result.consistencyScore,
      activeDaysLast30: result.activeDaysLast30,
    };
  }
}
