export enum AuditAction {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LOGIN = 'login',
  LOGIN_FAILED = 'login_failed',
  LOGOUT = 'logout',
  LOGOUT_ALL = 'logout_all',
  PERMISSION_CHANGE = 'permission_change',
  EXPORT = 'export',
  REGISTER = 'register',
  EMAIL_VERIFIED = 'email_verified',
  EMAIL_VERIFICATION_REQUESTED = 'email_verification_requested',
  PASSWORD_CHANGED = 'password_changed',
  PASSWORD_RESET_REQUESTED = 'password_reset_requested',
  PASSWORD_RESET_COMPLETED = 'password_reset_completed',
  ACCOUNT_LOCKED = 'account_locked',
  ACCOUNT_UNLOCKED = 'account_unlocked',
  SUSPICIOUS_LOGIN = 'suspicious_login',
  TOKEN_REFRESHED = 'token_refreshed',
  TOKEN_REUSE_DETECTED = 'token_reuse_detected',
  DEVICE_REVOKED = 'device_revoked',
  OAUTH_LINKED = 'oauth_linked',
}

export enum ActorType {
  USER = 'user',
  SYSTEM = 'system',
  SUPER_ADMIN = 'super_admin',
}
